### PR TITLE
Change pathlib version from v1.0.0 to v0.15.0

### PR DESCRIPTION
**Pull request by Mdaiki0730**
## Description
`github.com/chigopher/pathlib@v1.0.0` does not exist, so change the dependency version to the appropriate one.

Closes: #661

### CODE REVIEW

**Comment by tnasu** [comment]
If `pathlib` is had a dependency by the `mockery`, I think using the `replace` directive in the `go.mod` for excluding the dependency of `mockery`.

Here are recent updates of `mockery`. They may be going to upgrade a lot of things.
* https://github.com/Finschia/ostracon/pulls?q=mockery

**Comment by Mdaiki0730** [comment]
Does excluding a dependency mean replacing it with a specific version?

**Comment by ulbqb** [comment]
https://github.com/chigopher/pathlib/tags
I think this fix is better because pathlib@v1.0.0 doesn't exist.

**Review by ulbqb — APPROVED** [review]

**Review by tnasu — APPROVED** [review]
@Mdaiki0730 Yes, it does if `mockery` has a wrong dependency on `pathlib-v1.0.0`. But, I've confirmed mockery's dependency. It has an exact dependency now. Then I also don't have any comment.

```
% go mod graph | grep mockery
github.com/Finschia/ostracon github.com/vektra/mockery/v2@v2.30.17
github.com/vektra/mockery/v2@v2.30.17 github.com/chigopher/pathlib@v0.15.0
```

**Pull request merged**
